version: "3"

services:
  squid:
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - "51897:51897"
    container_name: 'squid'
    volumes:
      - ./logs:/var/log/squid
      - ./cache:/var/spool/squid
    restart: always
